version: "3.4"
services:
  csharp: #docker run -it -v ${PWD}:/work -w /work -p 5000:5000 aimvector/csharp:1.0.0 /bin/sh
    container_name: learn
    image: learn
    build:
      context: .
      target: build-env
    volumes:
    - ./:/work/
    ports:
      - 5000:5000
